### ISSUE TITLE
Missing exclude for rdo-network-scripts-openvswitch

### ISSUE THREAD

**Issue by Klaas-** [oVirt/ovirt-release#282]
I think you're missing an exclude for rdo-network-scripts-openvswitch in 
https://github.com/oVirt/ovirt-release/blob/235699adde80b059438af4c62ffe7449c8eaab03/ovirt-el8-stream-x86_64-deps.repo.in#L56-L64
and the other files where you exclude rdo-openvswitch

**Comment by sandrobonazzola** [comment]
@Klaas- I see it missing, does this cause any visible issue?

**Comment by sandrobonazzola** [comment]
Nevermind, I found the thread where this was discussed: https://lists.ovirt.org/archives/list/users@ovirt.org/thread/EHNPT3GUAKOQVCDZJQYGH655TVJED7SM/#7DKV3Q6JZCMEZR4MNH4BHXHJLEXIQVBS

**Comment by sandrobonazzola** [comment]
@Klaas- I would encourage you trying to submit a fix for this issue, I'll be happy to review it and help you get the fix in.
