### ISSUE TITLE
Move alma and rocky to consume CentOS Stream repos for Virtualization SIG

### ISSUE THREAD

**Issue by sandrobonazzola** [oVirt/ovirt-release#91]
CentOS Linux 8 repos are going to be archived to the vault and it won't be possible to update them anymore.
Preparing to switch to the repos provided for CentOS Stream also for Rocky and Alma.

**Comment by sandrobonazzola** [comment]
Looks like we have an issue with OpsTools repository on CentOS Stream:
```
package: ovirt-engine-4.4.10.6-1.el8.noarch from ovirt-4.4
  unresolved deps:
    collectd-disk
    collectd-write_http
    collectd-write_syslog
    collectd
    collectd-postgresql
package: ovirt-host-dependencies-4.4.9-2.el8.x86_64 from ovirt-4.4
  unresolved deps:
    collectd-virt
    collectd-disk
    collectd-write_http
    collectd-write_syslog
    collectd
    collectd-netlink
```

I'm going to sync with @mrunge when he'll be back next week.

**Comment by sandrobonazzola** [comment]
Added collectd from vault.centos.org as temporary workaround.

**Comment by mrunge** [comment]
Meanwhile, the packages landed http://mirror.centos.org/centos/8-stream/opstools/x86_64/collectd-5/Packages/

**Comment by sandrobonazzola** [comment]
Thank you very much @mrunge !

**Comment by sandrobonazzola** [comment]
Fixed, shipped live
